# Custom Language File for Launcher Customizer

[ejs.app]
title = "Sakura Launcher - Minecraft"

[ejs.landing]
mediaGitHubURL = "https://github.com/clementino29/SakuraLauncher"
mediaTwitterURL = "https://x.com/oorastb/status/1832143633010630803"
mediaInstagramURL = "https://www.instagram.com/reel/CsCWT_IoEBa/"
mediaYouTubeURL = "https://www.youtube.com/@clement_lmr"
mediaDiscordURL = "https://discord.com/channels/724651271251820565/724651271700611182"

[ejs.settings]
sourceGithubLink = "https://github.com/clementino29/SakuraLauncher"
supportLink = "https://github.com/clementino29/SakuraLauncher/issues"

[ejs.welcome]
welcomeHeader = "Merci d'avoir téléchargé le Sakura Launcher !"
welcomeDescription = "Nous vous souhaitons de passer un agréable moment sur le jeux !"
welcomeDescCTA = ""
