# Custom Language File for Launcher Customizer

[ejs.app]
title = "Sakura Launcher - Minecraft"

[ejs.landing]
mediaGitHubURL = "https://github.com/clementino29/SakuraLauncher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "https://www.youtube.com/@clement_lmr"
mediaDiscordURL = "#"

[ejs.settings]
sourceGithubLink = "https://github.com/clementino29/SakuraLauncher"
supportLink = "https://github.com/clementino29/SakuraLauncher/issues"

[ejs.welcome]
welcomeHeader = "Merci d'avoir téléchargé le Sakura Launcher !"
welcomeDescription = "Nous vous souhaitons de passer un agréable moment sur le jeux !"
welcomeDescCTA = ""
