# Custom Language File for Launcher Customizer

[ejs.app]
title = "Sakura Launcher - Minecraft"

[ejs.landing]
mediaGitHubURL = "https://github.com/clementino29/SakuraLauncher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/8zwNhfYZg7"

[ejs.settings]
sourceGithubLink = "https://github.com/clementino29/SakuraLauncher"
supportLink = "https://github.com/clementino29/SakuraLauncher/issues"

[ejs.welcome]
welcomeHeader = "Merci d'avoir téléchargé le Sakura Launcher !"
welcomeDescription = "Toute l'équipe vous remercie de votre participation à la Survie 2024 !"
welcomeDescCTA = "Nous vous souhaitons de passer un agréable moment sur le serveur !"
